import 'card_field.dart';
import 'card_template.dart';

/// Single source of truth for all template field specifications.
/// Drives prompt generation, normalization, Studio Deck editing, and contract tests.
class CardFieldRegistry {
  const CardFieldRegistry._();

  static List<CardFieldDescriptor> fieldsFor(CardTemplate template) {
    return switch (template) {
      CardTemplate.playerSpotlight => _playerSpotlight,
      CardTemplate.headlineQuote => _headlineQuote,
      CardTemplate.topStats => _topStats,
      CardTemplate.transferNews => _transferNews,
      CardTemplate.breakingNews => _breakingNews,
      CardTemplate.matchPreview => _matchPreview,
      CardTemplate.detailedScoreboard => _detailedScoreboard,
      CardTemplate.onThisDay => _onThisDay,
      CardTemplate.startingXI => _startingXI,
      CardTemplate.matchStatsComparison => _matchStatsComparison,
      CardTemplate.socialPost => _socialPost,
      CardTemplate.rivalry => _rivalry,
      CardTemplate.tableStandings => _tableStandings,
      CardTemplate.injuryReport => _injuryReport,
      CardTemplate.contractExpiry => _contractExpiry,
      CardTemplate.awardNominee => _awardNominee,
      CardTemplate.freeform => _freeform,
    };
  }

  // 1. Player Spotlight
  static const _playerSpotlight = [
    CardFieldDescriptor(
      key: 'playerName',
      label: 'Player Name',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['name', 'player'],
    ),
    CardFieldDescriptor(
      key: 'club',
      label: 'Club / Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aliases: ['team', 'currentClub'],
    ),
    CardFieldDescriptor(
      key: 'position',
      label: 'Position',
      type: CardFieldType.text,
      maxChars: 15,
      aliases: ['pos'],
    ),
    CardFieldDescriptor(
      key: 'rating',
      label: 'Match Rating',
      type: CardFieldType.rating,
      group: 'primary',
      aiHint: '0.0-10.0',
    ),
    CardFieldDescriptor(
      key: 'keyAction',
      label: 'Key Action / Badge',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'primary',
      aiHint: 'e.g. Hat-trick Wira / Gol Kemenangan',
    ),
    CardFieldDescriptor(
      key: 'keyQuote',
      label: 'Quote / Summary',
      type: CardFieldType.quote,
      maxChars: 90,
      group: 'secondary',
      aliases: ['quote', 'summary'],
    ),
    CardFieldDescriptor(
      key: 'goals',
      label: 'Goals',
      type: CardFieldType.number,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'assists',
      label: 'Assists',
      type: CardFieldType.number,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'minutesPlayed',
      label: 'Minutes',
      type: CardFieldType.number,
      group: 'secondary',
      aliases: ['minutes'],
    ),
    CardFieldDescriptor(
      key: 'nationality',
      label: 'Nationality',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'appearances',
      label: 'Appearances',
      type: CardFieldType.number,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'cleanSheets',
      label: 'Clean Sheets',
      type: CardFieldType.number,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'passes',
      label: 'Passes',
      type: CardFieldType.number,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'tackles',
      label: 'Tackles',
      type: CardFieldType.number,
      group: 'optional',
    ),
  ];

  // 2. Headline Quote
  static const _headlineQuote = [
    CardFieldDescriptor(
      key: 'quoteAuthor',
      label: 'Speaker / Author',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['author', 'speaker', 'playerName'],
    ),
    CardFieldDescriptor(
      key: 'subtext',
      label: 'The Quote',
      type: CardFieldType.quote,
      maxChars: 90,
      required: true,
      aliases: ['quote', 'statement', 'content'],
    ),
    CardFieldDescriptor(
      key: 'headline',
      label: 'Headline Hook',
      type: CardFieldType.text,
      maxChars: 60,
      required: true,
      aliases: ['title'],
    ),
    CardFieldDescriptor(
      key: 'authorTitle',
      label: 'Author Role / Title',
      type: CardFieldType.text,
      maxChars: 30,
      group: 'secondary',
      aliases: ['title', 'role', 'club'],
    ),
    CardFieldDescriptor(
      key: 'category',
      label: 'Category Tag',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'relatedTeams',
      label: 'Related Club',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
      aliases: ['club', 'team'],
    ),
  ];

  // 3. Top Stats
  static const _topStats = [
    CardFieldDescriptor(
      key: 'matchContext',
      label: 'Match Context',
      type: CardFieldType.text,
      maxChars: 30,
      required: true,
      aliases: ['context', 'title', 'headline'],
    ),
    CardFieldDescriptor(
      key: 'stats',
      label: 'Top 3 Statistics',
      type: CardFieldType.list,
      maxChars: 40,
      required: true,
      aiHint: 'Exactly 3 objects with label, value, context',
    ),
  ];

  // 4. Transfer News
  static const _transferNews = [
    CardFieldDescriptor(
      key: 'playerName',
      label: 'Player Name',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['player', 'name'],
    ),
    CardFieldDescriptor(
      key: 'action',
      label: 'Transfer Status',
      type: CardFieldType.text,
      maxChars: 15,
      aiHint: 'ONE WORD: SAH / DIPINJAM / SELESAI / KHABAR_ANGIN',
    ),
    CardFieldDescriptor(
      key: 'fromTeam',
      label: 'From Club',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aliases: ['currentClub', 'club', 'fromClub'],
    ),
    CardFieldDescriptor(
      key: 'toTeam',
      label: 'To Club',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aliases: ['newClub', 'destinationTeam', 'toClub'],
    ),
    CardFieldDescriptor(
      key: 'fee',
      label: 'Transfer Fee',
      type: CardFieldType.money,
      maxChars: 12,
      aiHint: 'Keep currency e.g. €85M / RM2.5M / Percuma',
    ),
    CardFieldDescriptor(
      key: 'contractLength',
      label: 'Contract Length',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'secondary',
      aiHint: 'e.g. 5 Tahun (2029)',
    ),
    CardFieldDescriptor(
      key: 'transferType',
      label: 'Transfer Type',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'secondary',
      aliases: ['type'],
    ),
    CardFieldDescriptor(
      key: 'quote',
      label: 'Player Quote / Context',
      type: CardFieldType.quote,
      maxChars: 90,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'feeCategory',
      label: 'Fee Category',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'medicalCompleted',
      label: 'Medical Done',
      type: CardFieldType.bool_,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'workPermit',
      label: 'Work Permit',
      type: CardFieldType.bool_,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'agentName',
      label: 'Agent Name',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
  ];

  // 5. Breaking News
  static const _breakingNews = [
    CardFieldDescriptor(
      key: 'headline',
      label: 'Headline',
      type: CardFieldType.text,
      maxChars: 60,
      required: true,
      aliases: ['title'],
    ),
    CardFieldDescriptor(
      key: 'subtext',
      label: 'Summary / Details',
      type: CardFieldType.text,
      maxChars: 90,
      required: true,
      aliases: ['content', 'details'],
    ),
    CardFieldDescriptor(
      key: 'label',
      label: 'Badge Label',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'primary',
      aiHint: 'e.g. RASMI / TERKINI',
    ),
    CardFieldDescriptor(
      key: 'impactRating',
      label: 'Impact (1-5)',
      type: CardFieldType.number,
      group: 'secondary',
      aiHint: '1 to 5',
    ),
    CardFieldDescriptor(
      key: 'relatedTeams',
      label: 'Related Club',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
      aliases: ['club', 'team'],
    ),
  ];

  // 6. Match Preview
  static const _matchPreview = [
    CardFieldDescriptor(
      key: 'homeTeam',
      label: 'Home Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'awayTeam',
      label: 'Away Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'competition',
      label: 'Competition',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['league', 'tournament'],
    ),
    CardFieldDescriptor(
      key: 'kickoffTime',
      label: 'Kickoff / Match Time',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'primary',
      aliases: ['matchTime', 'time'],
    ),
    CardFieldDescriptor(
      key: 'stadium',
      label: 'Stadium / Venue',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'secondary',
      aliases: ['venue'],
    ),
    CardFieldDescriptor(
      key: 'homeForm',
      label: 'Home Form',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'secondary',
      aiHint: 'e.g. W-W-D-W-L',
    ),
    CardFieldDescriptor(
      key: 'awayForm',
      label: 'Away Form',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'secondary',
      aiHint: 'e.g. D-W-L-W-W',
    ),
    CardFieldDescriptor(
      key: 'tvChannel',
      label: 'Broadcast / TV',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'referee',
      label: 'Referee',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'weather',
      label: 'Weather',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'capacity',
      label: 'Capacity',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
  ];

  // 7. Detailed Scoreboard
  static const _detailedScoreboard = [
    CardFieldDescriptor(
      key: 'homeTeam',
      label: 'Home Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'awayTeam',
      label: 'Away Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'homeScore',
      label: 'Home Score',
      type: CardFieldType.number,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'awayScore',
      label: 'Away Score',
      type: CardFieldType.number,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'competition',
      label: 'Competition',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'primary',
      aliases: ['league'],
    ),
    CardFieldDescriptor(
      key: 'matchStatus',
      label: 'Match Status',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'primary',
      aiHint: 'e.g. FT / LIVE / HT',
    ),
    CardFieldDescriptor(
      key: 'homeScorers',
      label: 'Home Scorers',
      type: CardFieldType.text,
      maxChars: 60,
      group: 'secondary',
      aiHint: "e.g. Haaland 23', 67'",
    ),
    CardFieldDescriptor(
      key: 'awayScorers',
      label: 'Away Scorers',
      type: CardFieldType.text,
      maxChars: 60,
      group: 'secondary',
      aiHint: "e.g. Saka 45'",
    ),
    CardFieldDescriptor(
      key: 'possession',
      label: 'Possession',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'secondary',
      aiHint: 'e.g. 58%',
    ),
    CardFieldDescriptor(
      key: 'shotsOnTarget',
      label: 'Shots on Target',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'secondary',
      aiHint: 'e.g. 7(14)',
    ),
    CardFieldDescriptor(
      key: 'corners',
      label: 'Corners',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'fouls',
      label: 'Fouls',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'yellowCards',
      label: 'Yellow Cards',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'redCards',
      label: 'Red Cards',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'attendance',
      label: 'Attendance',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'referee',
      label: 'Referee',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'penaltyShootout',
      label: 'Penalties',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'assistProviders',
      label: 'Assists',
      type: CardFieldType.text,
      maxChars: 40,
      group: 'optional',
    ),
  ];

  // 8. On This Day
  static const _onThisDay = [
    CardFieldDescriptor(
      key: 'dateLabel',
      label: 'Date Label',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aiHint: 'e.g. 2 Mei 2016',
    ),
    CardFieldDescriptor(
      key: 'yearsAgo',
      label: 'Years Ago',
      type: CardFieldType.number,
      required: true,
      aiHint: 'e.g. 8',
    ),
    CardFieldDescriptor(
      key: 'headline',
      label: 'Moment Headline',
      type: CardFieldType.text,
      maxChars: 60,
      required: true,
      aliases: ['title'],
    ),
    CardFieldDescriptor(
      key: 'competition',
      label: 'Competition',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'primary',
      aliases: ['tournament'],
    ),
    CardFieldDescriptor(
      key: 'significance',
      label: 'Historical Significance',
      type: CardFieldType.text,
      maxChars: 90,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'result',
      label: 'Match Result',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'venue',
      label: 'Venue',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'attendance',
      label: 'Attendance',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'keyStats',
      label: 'Key Stats',
      type: CardFieldType.list,
      group: 'optional',
    ),
  ];

  // 9. Starting XI
  static const _startingXI = [
    CardFieldDescriptor(
      key: 'teamName',
      label: 'Team Name',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aliases: ['team', 'club'],
    ),
    CardFieldDescriptor(
      key: 'formation',
      label: 'Formation',
      type: CardFieldType.text,
      maxChars: 10,
      required: true,
      aiHint: 'e.g. 4-3-3 / 3-4-2-1',
    ),
    CardFieldDescriptor(
      key: 'manager',
      label: 'Manager / Coach',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'primary',
      aliases: ['coach'],
    ),
    CardFieldDescriptor(
      key: 'starters',
      label: '11 Starters',
      type: CardFieldType.list,
      required: true,
      aiHint: 'List of 11 objects: number, name',
    ),
    CardFieldDescriptor(
      key: 'subs',
      label: 'Substitutes',
      type: CardFieldType.list,
      group: 'secondary',
      aiHint: 'List of up to 7 objects: number, name',
    ),
    CardFieldDescriptor(
      key: 'captain',
      label: 'Captain',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'keyAbsences',
      label: 'Key Absences',
      type: CardFieldType.text,
      maxChars: 60,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'tactics',
      label: 'Tactical Focus',
      type: CardFieldType.text,
      maxChars: 40,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'viceCaptain',
      label: 'Vice Captain',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'averageAge',
      label: 'Average Age',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'injuredPlayers',
      label: 'Injured',
      type: CardFieldType.text,
      maxChars: 40,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'suspendedPlayers',
      label: 'Suspended',
      type: CardFieldType.text,
      maxChars: 40,
      group: 'optional',
    ),
  ];

  // 10. Match Stats Comparison
  static const _matchStatsComparison = [
    CardFieldDescriptor(
      key: 'homeTeam',
      label: 'Home Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'awayTeam',
      label: 'Away Team',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'stats',
      label: 'Comparison Stats',
      type: CardFieldType.list,
      required: true,
      aiHint: 'List of comparison objects: label, homeValue, awayValue',
    ),
  ];

  // 11. Social Post
  static const _socialPost = [
    CardFieldDescriptor(
      key: 'name',
      label: 'Account Name',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['author', 'user'],
    ),
    CardFieldDescriptor(
      key: 'handle',
      label: 'Username / Handle',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aiHint: 'with @ prefix',
      aliases: ['username'],
    ),
    CardFieldDescriptor(
      key: 'content',
      label: 'Post Content',
      type: CardFieldType.text,
      maxChars: 120,
      required: true,
      aliases: ['headline', 'text', 'post'],
    ),
    CardFieldDescriptor(
      key: 'metrics',
      label: 'Social Metrics',
      type: CardFieldType.text,
      maxChars: 30,
      group: 'primary',
      aiHint: 'e.g. 1.2M Views • 45K Likes',
      aliases: ['subtext'],
    ),
    CardFieldDescriptor(
      key: 'timestamp',
      label: 'Timestamp',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'secondary',
      aiHint: 'e.g. 2j lalu • 14 Mei',
    ),
    CardFieldDescriptor(
      key: 'verified',
      label: 'Verified Badge',
      type: CardFieldType.bool_,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'followers',
      label: 'Followers',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'shares',
      label: 'Shares',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'bookmarks',
      label: 'Bookmarks',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'mediaType',
      label: 'Media Tag',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'isEdited',
      label: 'Edited Flag',
      type: CardFieldType.bool_,
      group: 'optional',
    ),
  ];

  // 12. Rivalry
  static const _rivalry = [
    CardFieldDescriptor(
      key: 'player1Name',
      label: 'Side 1 Name',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['player1', 'team1'],
    ),
    CardFieldDescriptor(
      key: 'player2Name',
      label: 'Side 2 Name',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['player2', 'team2'],
    ),
    CardFieldDescriptor(
      key: 'matchContext',
      label: 'Rivalry Context',
      type: CardFieldType.text,
      maxChars: 30,
      required: true,
      aliases: ['title', 'context'],
    ),
    CardFieldDescriptor(
      key: 'verdict',
      label: 'Verdict / Headline',
      type: CardFieldType.text,
      maxChars: 60,
      group: 'primary',
    ),
    CardFieldDescriptor(
      key: 'headToHead',
      label: 'Head-to-Head Record',
      type: CardFieldType.text,
      maxChars: 30,
      group: 'secondary',
      aiHint: 'e.g. 15 Wins - 8 Draws - 12 Wins',
    ),
    CardFieldDescriptor(
      key: 'player1Stats',
      label: 'Side 1 Stats',
      type: CardFieldType.list,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'player2Stats',
      label: 'Side 2 Stats',
      type: CardFieldType.list,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'compareType',
      label: 'Comparison Type',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'totalMatches',
      label: 'Total Matches',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'draws',
      label: 'Draws',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'player1Trophies',
      label: 'Side 1 Trophies',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'player2Trophies',
      label: 'Side 2 Trophies',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'predictionConfidence',
      label: 'Confidence',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
  ];

  // 13. Table Standings
  static const _tableStandings = [
    CardFieldDescriptor(
      key: 'leagueName',
      label: 'League Name',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
      aliases: ['league', 'tournament'],
    ),
    CardFieldDescriptor(
      key: 'matchday',
      label: 'Matchday',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'primary',
      aiHint: 'e.g. Perlawanan 28',
    ),
    CardFieldDescriptor(
      key: 'highlightedTeam',
      label: 'Highlight Team',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'primary',
      aliases: ['team'],
    ),
    CardFieldDescriptor(
      key: 'standings',
      label: 'Standings Rows',
      type: CardFieldType.list,
      required: true,
      aiHint: 'List of table rows: position, teamName, played, won, drawn, lost, points, form',
    ),
    CardFieldDescriptor(
      key: 'promotionZone',
      label: 'Promotion Cutoff',
      type: CardFieldType.number,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'relegationZone',
      label: 'Relegation Cutoff',
      type: CardFieldType.number,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'gamesInHand',
      label: 'Games in Hand',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'pointsBehindLeader',
      label: 'Pts Behind Leader',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'topScorer',
      label: 'Top Scorer',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'topAssists',
      label: 'Top Assists',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
  ];

  // 14. Injury Report
  static const _injuryReport = [
    CardFieldDescriptor(
      key: 'teamName',
      label: 'Team Name',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aliases: ['team', 'club'],
    ),
    CardFieldDescriptor(
      key: 'reportDate',
      label: 'Report Date',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'primary',
    ),
    CardFieldDescriptor(
      key: 'nextMatch',
      label: 'Next Match Context',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'primary',
    ),
    CardFieldDescriptor(
      key: 'injuries',
      label: 'Injury List',
      type: CardFieldType.list,
      required: true,
      aiHint: 'List of injury items: playerName, injury, status, position, recoveryPercentage, isLongTerm, surgeryRequired',
    ),
    CardFieldDescriptor(
      key: 'doubtfits',
      label: 'Doubtful Players',
      type: CardFieldType.list,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'returns',
      label: 'Returning Players',
      type: CardFieldType.list,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'recoveryPercentage',
      label: 'Squad Health %',
      type: CardFieldType.text,
      maxChars: 10,
      group: 'optional',
    ),
  ];

  // 15. Contract Expiry
  static const _contractExpiry = [
    CardFieldDescriptor(
      key: 'teamName',
      label: 'Team Name',
      type: CardFieldType.text,
      maxChars: 20,
      required: true,
      aliases: ['team', 'club'],
    ),
    CardFieldDescriptor(
      key: 'seasonYear',
      label: 'Expiry Season',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'primary',
      aiHint: 'e.g. Jun 2025 / 2024/25',
    ),
    CardFieldDescriptor(
      key: 'expiringPlayers',
      label: 'Expiring Players',
      type: CardFieldType.list,
      required: true,
      aiHint: 'List of contract players: playerName, position, expiresIn, marketValue, status, wage, askingPrice, interestLevel, negotiationProgress, previousClub',
    ),
    CardFieldDescriptor(
      key: 'renewals',
      label: 'Pending Renewals',
      type: CardFieldType.list,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'wage',
      label: 'Total Wage Load',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'askingPrice',
      label: 'Target Asking Price',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'interestLevel',
      label: 'Market Interest',
      type: CardFieldType.text,
      maxChars: 15,
      group: 'optional',
    ),
  ];

  // 16. Award Nominee
  static const _awardNominee = [
    CardFieldDescriptor(
      key: 'awardName',
      label: 'Award Name',
      type: CardFieldType.text,
      maxChars: 30,
      required: true,
      aliases: ['award'],
    ),
    CardFieldDescriptor(
      key: 'category',
      label: 'Award Category',
      type: CardFieldType.text,
      maxChars: 25,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'currentFavorite',
      label: 'Current Favorite',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'primary',
      aliases: ['favorite'],
    ),
    CardFieldDescriptor(
      key: 'nominees',
      label: 'Nominee List',
      type: CardFieldType.list,
      required: true,
      aiHint: 'List of nominees: playerName, club, achievement, odds, isFavorite, previousWinner, votes',
    ),
    CardFieldDescriptor(
      key: 'ceremonyDate',
      label: 'Ceremony Date',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'votingDeadline',
      label: 'Voting Deadline',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'secondary',
    ),
    CardFieldDescriptor(
      key: 'votingMethod',
      label: 'Voting Method',
      type: CardFieldType.text,
      maxChars: 20,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'totalNominees',
      label: 'Total Nominees',
      type: CardFieldType.number,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'venue',
      label: 'Venue',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
    CardFieldDescriptor(
      key: 'host',
      label: 'Host',
      type: CardFieldType.text,
      maxChars: 25,
      group: 'optional',
    ),
  ];

  // 17. Freeform (Draggable text elements)
  static const _freeform = [
    CardFieldDescriptor(
      key: 'headline',
      label: 'Headline',
      type: CardFieldType.text,
      maxChars: 60,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'subtext',
      label: 'Body Text',
      type: CardFieldType.quote,
      maxChars: 90,
      required: true,
    ),
    CardFieldDescriptor(
      key: 'microStat',
      label: 'Micro Stat / Tag',
      type: CardFieldType.text,
      maxChars: 24,
      group: 'secondary',
    ),
  ];
}
